name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          ini-values: php_memory_limit=4096M
      - run: make app-install
      - run: make ci

